CREATE TABLE noteful_notes(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    note_name TEXT NOT NULL,
    content TEXT NOT NULL,
    date_modified TIMESTAMP NOT NULL DEFAULT now(),
    folder_id INTEGER REFERENCES noteful_folders(id)
    ON DELETE CASCADE NOT NULL
);